config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("oncallpack.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("contacts/", include("oncallpack.contacts.urls", namespace="contacts")),
    path("search/", include("oncallpack.search.urls", namespace="search")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

oncallpack/contacts/urls.py
from django.views.generic.base import TemplateView

from django.urls import path

from contacts.views import (
    OrganisationListView,
    AirportListView,
    AirportCreateView,
    AirportDetailView,
    AirportContactsView,
    airport_update,
    PoliceListView,
)

app_name = "contacts"
urlpatterns = [
    path("", TemplateView.as_view(template_name="contacts/contacts_index.html")),
    path("organisations/", OrganisationListView.as_view(), name="organisations_list"),
    path("airports/", AirportListView.as_view(), name="airports_list"),
    path("police/", PoliceListView.as_view(), name="police_list"),
    path("create-airport/", AirportCreateView.as_view(), name="airport_create"),
    path("update-airport/<int:org_id>", airport_update, name="airport_update"),
    path("airport/<int:pk>", AirportDetailView.as_view(), name="airport_detail"),
    path("airport-contacts/<int:pk>", AirportContactsView.as_view(), name="airport_detail_contacts")
]

oncallpack/search/urls.py
from django.urls import path

from search.views import SearchView

app_name = "search"
urlpatterns = [
    path("", SearchView.as_view()),
]

oncallpack/users/urls.py
from django.urls import path

from oncallpack.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

oncallpack/contacts/models.py
from itertools import chain
from typing import Iterable, Union

from django.db import models
from django.db.models import Q
from django.urls import reverse


class OrganisationManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                Q(name__icontains=query)
                | Q(icao_code__icontains=query)
                | Q(iata_code__icontains=query)
            )
            qs = qs.filter(
                or_lookup
            ).distinct()  # distinct() is often necessary with Q lookups
        return qs


class PersonManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            qs = qs.filter(name__icontains=query).all()
        return qs


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    'created' and 'modified' fields.
    """

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Mode(TimeStampedModel):
    name = models.CharField(max_length=50, blank=False)

    def __str__(self):
        return self.name


class Role(TimeStampedModel):
    name = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return self.name


class Type(TimeStampedModel):
    name = models.CharField(max_length=35, blank=False)
    description = models.TextField()

    def __str__(self):
        return self.name


class KeyContact(TimeStampedModel):
    name = models.CharField(max_length=100, blank=False)
    notes = models.TextField(max_length=250, blank=True, null=True)
    tel = models.CharField(max_length=30, null=True, blank=True)
    fax = models.CharField(max_length=30, null=True, blank=True)
    surefax = models.CharField(max_length=30, null=True, blank=True)
    mobile = models.CharField(max_length=30, null=True, blank=True)
    tfh = models.BooleanField(default=False, verbose_name="24hr")
    home = models.CharField(max_length=30, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    priority = models.IntegerField(
        default=10
    )  # for sorting on detail page - low is high priority
    organisation = models.ForeignKey(
        "Organisation", null=True, blank=True, on_delete=models.CASCADE
    )

    @property
    def klass(self):
        return str(self.__class__)

    @property
    def tfh_template(self):
        """
        Pretty self.tfh for template (i.e. not True, False).
        """
        if self.tfh:
            return "YES"
        elif self.tfh is False:
            return "NO"

    def __str__(self):
        return f"{self.name}"


class Organisation(TimeStampedModel):
    name = models.CharField(max_length=100, blank=False)
    mode = models.ForeignKey(Mode, on_delete=models.CASCADE, null=True, blank=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE, blank=True)
    website = models.CharField(max_length=100, null=True, blank=True)
    main_phone = models.CharField(max_length=30, null=True, blank=True)
    iata_code = models.CharField(
        max_length=3, null=True, blank=True, verbose_name="IATA code"
    )
    icao_code = models.CharField(
        max_length=4, null=True, blank=True, verbose_name="ICAO code"
    )
    local_police = models.ForeignKey(
        "Organisation",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="police_for",
    )

    objects = OrganisationManager()

    @property
    def all_persons(self):
        people = self.people.all()
        key_contacts = self.keycontact_set.all()
        return list(chain(people, key_contacts))

    @property
    def directed_person(self):
        return return_person_with_role_in_organisation(
            role_name="Directed Person", organisation=self
        )

    @property
    def people_no_directed_party(self):
        qs = self.people.exclude(role__name="Directed Person")
        return qs

    def get_absolute_url(self):
        return reverse("contacts:airport_detail", args=[str(self.id)])

    def __str__(self):
        return self.name


class Person(TimeStampedModel):
    name = models.CharField(max_length=100, blank=False)
    organisation = models.ForeignKey(
        Organisation, on_delete=models.CASCADE, related_name="people"
    )
    role = models.ManyToManyField(Role)
    tel = models.CharField(max_length=30, null=True, blank=True)
    fax = models.CharField(max_length=30, null=True, blank=True)
    surefax = models.CharField(max_length=30, null=True, blank=True)
    mobile = models.CharField(max_length=30, null=True, blank=True)
    home = models.CharField(max_length=30, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def klass(self):
        return str(__class__)

    objects = PersonManager()


class RemoteAmendment(TimeStampedModel):
    person_to_amend = models.ForeignKey(Person, on_delete=models.CASCADE, null=True, blank=True)
    key_contact_to_amend = models.ForeignKey(KeyContact, on_delete=models.CASCADE, null=True, blank=True)
    new_tel = models.CharField(max_length=30, null=True, blank=True)
    new_fax = models.CharField(max_length=30, null=True, blank=True)
    new_surefax = models.CharField(max_length=30, null=True, blank=True)
    new_mobile = models.CharField(max_length=30, null=True, blank=True)
    new_home = models.CharField(max_length=30, null=True, blank=True)
    new_priority = models.IntegerField(default=10, null=True, blank=True)
    new_role = models.CharField(max_length=100, null=True, blank=True)
    new_notes = models.TextField(max_length=250, null=True, blank=True)

# --- SELECTORS --- #

def return_person_with_role_in_organisation(
    *, role_name: str, organisation: Organisation
) -> Union[Person, None]:
    dp_role = Role.objects.get(name=role_name)
    directed_persons = Person.objects.filter(role=dp_role)
    for p in directed_persons:
        if p.organisation == organisation:
            return p
    return None

# --- END OF SELECTORS --- #

oncallpack/search/models.py
from django.db import models

# Create your models here.

oncallpack/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

oncallpack/contacts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView

from .forms import AirportCreateForm, AirportFormSet, KeyContactsHelper
from .models import Organisation, Type


class OrganisationListView(LoginRequiredMixin, ListView):
    model = Organisation


class AirportListView(LoginRequiredMixin, ListView):
    template_name = "contacts/airports_list.html"

    def get_queryset(self):
        self.airport_type = get_object_or_404(Type, name="Airport")
        return Organisation.objects.filter(type=self.airport_type)


@login_required
def airport_update(request, org_id):
    if org_id:
        org = Organisation.objects.get(pk=org_id)
    else:
        org = Organisation()
    org_form = AirportCreateForm(instance=org)
    #   AirportFormSet = inlineformset_factory(
    #       Organisation,
    #       KeyContact,
    #       fields=("name", "notes",  "tel", "fax", "surefax", "mobile", "home", "priority", "tfh"),
    #       extra=2,
    #       can_delete=False,
    #   )
    formset = AirportFormSet(instance=org)
    if request.method == "POST":
        org_form = AirportCreateForm(request.POST)
        if org_id:
            org_form = AirportCreateForm(request.POST, instance=org)

        formset = AirportFormSet(request.POST, request.FILES)

        if org_form.is_valid():
            created_org = org_form.save(commit=False)
            formset = AirportFormSet(request.POST, request.FILES, instance=created_org)

            if formset.is_valid():
                created_org.save()
                formset.save()
                return HttpResponseRedirect(org.get_absolute_url())
    keycontacts_helper = KeyContactsHelper()
    return render(
        request,
        "contacts/update_airport.html",
        {
            "org_id": org_id,
            "org_form": org_form,
            "formset": formset,
            "keycontacts_helper": keycontacts_helper,
        },
    )


class AirportCreateView(LoginRequiredMixin, CreateView):
    model = Organisation
    template_name = "contacts/create_airport.html"
    form_class = AirportCreateForm
    success_url = reverse_lazy("contacts:airports_list")

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        airport_form = self.get_form(form_class)
        formset = AirportFormSet()

        return self.render_to_response(
            self.get_context_data(formset=formset, airport_form=airport_form)
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        airport_form = self.get_form(form_class)
        formset = AirportFormSet(self.request.POST)

        if airport_form.is_valid() and formset.is_valid():
            return self.form_valid(airport_form, formset)

    def form_valid(self, airport_form, formset):
        self.object = airport_form.save()
        formset.instance = self.object
        formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, airport_form, formset):
        return self.render_to_response(
            self.get_context_data(airport_form=airport_form, formset=formset)
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        keycontacts_helper = KeyContactsHelper

        if self.request.POST:
            ctx["airport_form"] = AirportCreateForm(self.request.POST)
            ctx["formset"] = AirportFormSet(self.request.POST)
            ctx["keycontacts_helper"] = keycontacts_helper
        else:
            ctx["airport_form"] = AirportCreateForm()
            ctx["formset"] = AirportFormSet()
            ctx["keycontacts_helper"] = keycontacts_helper
        return ctx


class AirportDetailView(LoginRequiredMixin, DetailView):
    # TODO Remove dependency: commment next two lines out to migrate for first time
    ap = Type.objects.filter(name="Airport").first()
    queryset = Organisation.objects.filter(type=ap)
    template_name = "contacts/airport_detail.html"

class AirportContactsView(DetailView):
    ap = Type.objects.filter(name="Airport").first()
    queryset = Organisation.objects.filter(type=ap)
    template_name = "contacts/airport_detail_contacts.html"

class PoliceListView(LoginRequiredMixin, ListView):
    template_name = "contacts/police_list.html"

    def get_queryset(self):
        self.police_type = get_object_or_404(Type, name="Police Force")
        return Organisation.objects.filter(type=self.police_type)

oncallpack/search/views.py
from itertools import chain

from django.views.generic import ListView

from contacts.models import Organisation, Person


class SearchView(ListView):
    template_name = "search/index.html"
    paginate_by = 20
    count = 0

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["count"] = self.count or 0
        context["query"] = self.request.GET.get("q")
        # if the view contains a query, we want the "Search Results" heading in the template
        if len(self.request.GET.dict().keys()) > 0:
            context["search_results"] = True
        # otherwise not
        else:
            context["search_results"] = False
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get("q", None)

        if query is not None:
            org_results = Organisation.objects.search(query)
            person_results = Person.objects.search(query)

            queryset_chain = chain(org_results, person_results)

            qs = sorted(queryset_chain, key=lambda instance: instance.pk, reverse=True)
            self.count = len(qs)  # since qs is a list
            return qs
        return Organisation.objects.none()  # just an empty queryset as default

oncallpack/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

oncallpack/templates/contacts/airport_detail.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<div class="container-fluid">
        <div class="card text-white bg-primary mb-3">
            <div class="card-body">
                <h2 class="card-title">{{ object.name }}</h2>
                <h6 class="card-subtitle mb-2 text-light">Updated: {{ object.modified|date:"d F Y" }}</h6>
                <div class="container-fluid">
                    <div class="row py-2">
                        <div class="col-sm">
                            <strong>IATA</strong>: {{ object.iata_code }}
                        </div>
                        <div class="col-sm">
                            <strong>ICAO</strong>: {{ object.icao_code }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm">
                            <strong>General No: </strong>{{ object.main_phone }}
                        </div>
                        <div class="col-sm">
                            <strong>Web site: </strong>{{ object.website }}
                        </div>
                    </div>
                </div>
            </div> 
            <div class="container">
                <a href="{% url 'contacts:airport_update' object.id %}" class="text-light">Edit</a> 
            </div>
        </div>

        {% for o in object.keycontact_set.all|dictsort:"priority" %}
        <div class="card bg-warning my-1 my-1">
           <div class="card-body">
            <h3 class="card-title">{{ o.name }}</h3>
            <h6 class="card-subtitle mb-2 text-muted">Updated: {{ o.modified|date:"d F Y" }}</h6>
            <div class="list-group">
                <li class="list-group-item"><strong>Notes:</strong> {{ o.notes }}</li>
                <li class="list-group-item"><strong>Tel:</strong> {{ o.tel }}</li>
                <li class="list-group-item"><strong>Fax:</strong> {{ o.fax }}</li>
                <li class="list-group-item"><strong>Surefax:</strong> {{ o.surefax }}</li>
                <li class="list-group-item"><strong>Mobile:</strong> {{ o.mobile }}</li>
                <li class="list-group-item"><strong>Home:</strong> {{ o.home }}</li>
              <li class="list-group-item"><strong>Email:</strong> <a href="mailto:{{ o.email }}">{{ o.email }}</a></li>
                {% if o.tfh_template == "NO" %}
                <li class="list-group-item bg-danger"><strong>24hr:</strong><span class="text-light"> {{ o.tfh_template }}</span></li>
                {% else %}
                    <li class="list-group-item"><strong>24hr:</strong> {{ o.tfh_template }}</li>
                {% endif %}
            </div>
           </div>
        </div>
        {% endfor %}


        {% if object.directed_person %}
        <div class="card my-1">
           <div class="card-body">
               <h3 class="card-title">Directed Person</h3>
               <h5>{{ object.directed_person.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Updated: {{ object.modified|date:"d F Y" }}</h6>
                <div class="list-group list-group-flush">
                    <li class="list-group-item list-group-item-action"><strong>Tel:</strong> {{ object.directed_person.tel }}</li>
                    <li class="list-group-item list-group-item-action"><strong>Mobile:</strong> {{ object.directed_person.mobile }}</li>
                    <li class="list-group-item list-group-item-action"><strong>Home:</strong> {{ object.directed_person.home }}</li>
                    <li class="list-group-item"><strong>Fax:</strong> {{ object.directed_person.fax }}</li>
                    <li class="list-group-item"><strong>Surefax:</strong> {{ object.directed_person.surefax }}</li>
                </div>
           </div> 
        </div>
        {% endif %}

        <!-- - no Directed Person in this queryset --> 
        {% for o in object.people_no_directed_party %}
        <div class="card my-1">
           <div class="card-body">
               <h3 class="card-title">{{ o.role.first.name }}</h3>
               <h5>{{ o.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Updated: {{ o.modified|date:"d F Y" }}</h6>
                <div class="list-group list-group-flush">
                    <li class="list-group-item list-group-item-action"><strong>Tel:</strong> {{ o.tel }}</li>
                    <li class="list-group-item list-group-item-action"><strong>Mobile:</strong> {{ o.mobile }}</li>
                    <li class="list-group-item list-group-item-action"><strong>Home:</strong> {{ o.home }}</li>
                    <li class="list-group-item"><strong>Fax:</strong> {{ o.fax }}</li>
                    <li class="list-group-item"><strong>Surefax:</strong> {{ o.surefax }}</li>
                </div>
           </div> 
        </div>
        {% endfor %}


        <div class="card my-2 bg-info">
            <div class="card-body">
                <h3 class="card-title">{{ object.local_police.name|upper }}</h3>
                <h6 class="card-subtitle mb-2 text-light">Updated: {{ object.modified|date:"d F Y" }}</h6>
                <div class="list-group">
                    <li class="list-group-item"><strong>Tel:</strong> {{ object.local_police.main_phone }}</li>
                </div>
            </div>
        </div>
                </div>
            </div>
        </div>
</div>
{% endblock content %}

oncallpack/templates/contacts/airport_detail_contacts.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}{{ object.name }}{% endblock %}

{% block content %}

  <h2>{{ object.name }}</h2>
  <h4>{{ object.icao_code }}</h4>

{#  All this from https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_js_modal2&stacked=h#}
  <button type="button" class="btn btn-default btn-lg" id="myBtn">Login</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <form role="form">
            <div class="form-group">
              <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
              <input type="text" class="form-control" id="usrname" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
              <input type="text" class="form-control" id="psw" placeholder="Enter password">
            </div>
            <div class="checkbox">
              <label><input type="checkbox" value="" checked>Remember me</label>
            </div>
              <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
          <p>Not a member? <a href="#">Sign Up</a></p>
          <p>Forgot <a href="#">Password?</a></p>
        </div>
      </div>

    </div>
  </div>

  <script>
$(document).ready(function(){
    $("#myBtn").click(function(){
        $("#myModal").modal();
    });
});
</script>

{#  end of modal experiment #}


  {% for p in object.all_persons %}
    <div class="card-body">
      <div class="card my-1">
        <h3 class="card-title">{{ p.name }}</h3>
        <div class="list-group">
          <div class="list-group-item">
            {{ p.klass }} | {{  p.id }}
          </div>
          <div class="list-group-item">
            {% if p.notes %}
              {{ p.notes }}
          {% else %}
              No notes
            {% endif %}
          </div>
          <div class="list-group-item">
            {{ p.tel }}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

{%  endblock %}

oncallpack/templates/contacts/airports_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Organisations{% endblock %}

{% block content %}
<div class="container">
  <h2>Airports</h2>

  <table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Airport</th>
            <th>IATA</th>
            <th>ICAO</th>
            <th>Directed Person</th>
        </tr>
    </thead> 
    <tbody>
        {% for org in organisation_list %}
        <tr>
            <td><a href="{% url 'contacts:airport_detail' org.id %}">{{ org.name }}</a></td>
            <td>{{ org.iata_code }}</td>
            <td>{{ org.icao_code }}</td>
            <td>{{ org.directed_person }}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

oncallpack/templates/contacts/contacts_index.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Contacts{% endblock %}

{% block content %}

<div class="container">
  <h2>Contacts</h2>
  <p>This is where we link to all the Contacts-related items in the system.</p>

  <ul class="list-group">
      <li class="list-group-item"><i class="fas fa-plane-departure"></i> <a href={% url "contacts:airports_list" %}>Airports</a></li>
      <li class="list-group-item"><i class="fas fa-shuttle-van"></i> <a href={% url "contacts:police_list" %}>Police Forces</a></li> 
  </ul>
  
</div>

{% endblock content %}

oncallpack/templates/contacts/create_airport.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}Create New Airport Form{% endblock %}

{% block content %}

<h2>Create New Airport</h2>
<p>Some blurb here about what an airport is in this system. A place 
where planes take off and land, yeah?</p>

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card bg-primary text-light my-2 p-2">
                <form method="post" accept-charset="utf-8">
                {{ formset.management_form }}
                {{ formset.non_form_errors }}
                {% crispy airport_form %} 
            </div>
            <div class="card bg-warning my-2 p-2">
                {% crispy formset keycontacts_helper %}
                <input type="submit" value="Save" name="" id="" class="btn btn-primary"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

oncallpack/templates/contacts/organisation_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Organisations{% endblock %}

{% block content %}
<div class="container">
  <h2>Organisations</h2>

  <table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Organisation</th>
            <th>Mode</th>
            <th>Type</th>
        </tr>
    </thead> 
    <tbody>
        {% for org in organisation_list %}
        <tr>
            <td>{{ org.name }}</td>
            <td>{{ org.mode }}</td>
            <td>{{ org.type }}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

oncallpack/templates/contacts/police_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Police Forces{% endblock %}

{% block content %}
<div class="container">
  <h2>Police Forces</h2>

  <table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Police Force Name</th>
            <th>Web site</th>
            <th>Main Phone</th>
            <th>Primary Contact</th>
        </tr>
    </thead> 
    <tbody>
        {% for org in organisation_list %}
        <tr>
            <td>{{ org.name }}</td>
            <td>{{ org.website }}</td>
            <td>{{ org.main_phone }}</td>
            <td><strong>{{ org.key_contact.name }}</strong><br>
                {{ org.key_contact.tel }}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

oncallpack/templates/contacts/update_airport.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}Update Airport{% endblock %}

{% block content %}

<h2>Update Airport</h2>
<p>Some blurb here about what an airport is in this system. A place 
where planes take off and land, yeah?</p>

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card bg-primary text-light my-2 p-2">
                <form method="post" accept-charset="utf-8">{% csrf_token %}
                    {{ formset.management_form }}
                    {{ formset.non_form_errors }}
                    {% crispy org_form %}
            </div>
            <div class="card bg-warning my-2 p-2">
                    {% crispy formset keycontacts_helper %}
                <input type="submit" value="Save" name="" id="" class="btn btn-primary my-1"/>
                <a href="{% url "contacts:airport_detail" org_id %}" class="btn btn-danger my-1">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}